In [86]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
df = pd.read_csv("Documents\\Campus Recruitment.csv")
df

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..         ...    ...      ...            ...    ...         ...       ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 15 columns]

In [87]:
df= df.drop(['sl_no','salary'],axis='columns')

In [88]:
df.head()

gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p   degree_t  \
0      M  67.00   Others  91.00   Others  Commerce     58.00   Sci&Tech   
1      M  79.33  Central  78.33   Others   Science     77.48   Sci&Tech   
2      M  65.00  Central  68.00  Central      Arts     64.00  Comm&Mgmt   
3      M  56.00  Central  52.00  Central   Science     52.00   Sci&Tech   
4      M  85.80  Central  73.60  Central  Commerce     73.30  Comm&Mgmt   

  workex  etest_p specialisation  mba_p      status  
0     No     55.0         Mkt&HR  58.80      Placed  
1    Yes     86.5        Mkt&Fin  66.28      Placed  
2     No     75.0        Mkt&Fin  57.80      Placed  
3     No     66.0         Mkt&HR  59.43  Not Placed  
4     No     96.8        Mkt&Fin  55.50      Placed

In [89]:
df.select_dtypes('object')

gender    ssc_b    hsc_b     hsc_s   degree_t workex specialisation  \
0        M   Others   Others  Commerce   Sci&Tech     No         Mkt&HR   
1        M  Central   Others   Science   Sci&Tech    Yes        Mkt&Fin   
2        M  Central  Central      Arts  Comm&Mgmt     No        Mkt&Fin   
3        M  Central  Central   Science   Sci&Tech     No         Mkt&HR   
4        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin   
..     ...      ...      ...       ...        ...    ...            ...   
210      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin   
211      M   Others   Others   Science   Sci&Tech     No        Mkt&Fin   
212      M   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin   
213      F   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR   
214      M  Central   Others   Science  Comm&Mgmt     No         Mkt&HR   

         status  
0        Placed  
1        Placed  
2        Placed  
3    Not Placed  
4        Placed  
..          ...  
210      Placed  
211      Placed  
212      Placed  
213      Placed  
214  Not Placed  

[215 rows x 8 columns]

In [90]:
df['gender'].unique()

array(['M', 'F'], dtype=object)

In [91]:
df['ssc_b'].unique()

array(['Others', 'Central'], dtype=object)

In [92]:
df['hsc_s'].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [93]:
df['degree_t'].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [94]:
df['specialisation'].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [95]:
cat_columns = [x for x in df.select_dtypes('object').columns]
cat_columns

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [96]:
from sklearn.preprocessing import LabelEncoder

In [97]:
le = LabelEncoder()

In [98]:
for col in cat_columns:
    df[col] = le.fit_transform(df[col])

In [99]:
df.head()

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0       1  67.00      1  91.00      1      1     58.00         2       0   
1       1  79.33      0  78.33      1      2     77.48         2       1   
2       1  65.00      0  68.00      0      0     64.00         0       0   
3       1  56.00      0  52.00      0      2     52.00         2       0   
4       1  85.80      0  73.60      0      1     73.30         0       0   

   etest_p  specialisation  mba_p  status  
0     55.0               1  58.80       1  
1     86.5               0  66.28       1  
2     75.0               0  57.80       1  
3     66.0               1  59.43       0  
4     96.8               0  55.50       1

In [100]:
from sklearn.linear_model import LogisticRegression

In [101]:
lr_model = LogisticRegression(max_iter=10)

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
x = df.drop('status',axis='columns')
y = df['status']

In [104]:
x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [105]:
lr_model.fit(x,y)

E:\Users\devil\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=10)

In [106]:
lr_model.score(x_test,y_test)

0.8153846153846154

In [107]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200)

In [108]:
rfc.score(x_test,y_test)

0.9076923076923077

In [109]:
rfc_pred = rfc.predict(x_test)

In [110]:
rfc_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0])

In [127]:
from sklearn.metrics import classification_report,confusion_matrix

In [128]:
print(confusion_matrix(y_test,rfc_pred))

[[15  4]
 [ 2 44]]


In [130]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.88      0.79      0.83        19
           1       0.92      0.96      0.94        46

    accuracy                           0.91        65
   macro avg       0.90      0.87      0.88        65
weighted avg       0.91      0.91      0.91        65



In [117]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()

In [118]:
dtree.fit(x_train, y_train)

DecisionTreeClassifier()

In [119]:
prediction = dtree.predict(x_test)

In [121]:
from sklearn.metrics import classification_report,confusion_matrix

In [122]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.60      0.79      0.68        19
           1       0.90      0.78      0.84        46

    accuracy                           0.78        65
   macro avg       0.75      0.79      0.76        65
weighted avg       0.81      0.78      0.79        65



In [126]:
print(confusion_matrix(y_test,prediction))

[[15  4]
 [10 36]]
